package ru.test.task.servicies.errors

case object CustomException extends  Throwable("Exception")
